### ISSUE TITLE
Hide the status when moving within the same drive 

### ISSUE THREAD

**Issue by abrahammurciano** [jarun/advcpmv#15]
If I do
```
$ advmv -g /path/to/big/dir /path/in/same/drive
```

It will delay for a bit while it calculates the size of the directory, then it moves them instantly.

If the move is going to be instant, there's no need to show progress so the progress in such a scenario should either be suppressed or an option to suppress it should be available (so one can set an alias to always use).

**Comment by jarun** [comment]
Sorry, we are not going to add any pseudo-intelligence here.

**Comment by jarun** [comment]
The reasons why I want to avoid this are guarding against the cases like:

- src/target symlink(s)
- non-existent targets

I simply don't want to maintain such code when there is literally 0 to minimal RoI for contributing to open source.
I've been struggling with my dated and dead-slow personal laptop for a year now and could not collect enough to buy a new one.
Thank you for your understanding.
