### ISSUE TITLE
Can these two command(cp/mv) programs be compiled and integrated into the Openwrt system?

### ISSUE THREAD

**Issue by VPN-V2Ray** [jarun/advcpmv#20]
Can these two command(cp/mv) programs be compiled and integrated into the Openwrt system?

**Comment by SlrG** [comment]
I imagine this question would be better directed at the openwrt devs. If they are using the coreutils cp and mv commands and not some busybox implementation and if its possible to patch and compile coreutils for the openwrt linux kernel, it should be possible.

**Comment by jarun** [comment]
Second @SlrG. Not our call.
