### ISSUE TITLE
Coreutils 9.1 support

### ISSUE THREAD

**Issue by Vresod** [jarun/advcpmv#21]

**Comment by Zackptg5** [comment]
Have a test branch open if you want to test it out. You'll need to change the url to the 9.0-test branch

https://github.com/jarun/advcpmv/tree/9.1-test

**Comment by jarun** [comment]
Please raise the PR.

**Comment by Zackptg5** [comment]
Seems to work fine, I'll raise the PR

**Comment by jarun** [comment]
Closed at #22.
