### ISSUE TITLE
v9.3 patch's file paths lack prefixes and breaks patching

### ISSUE THREAD

**Issue by Anomalocaridid** [jarun/advcpmv#32]
The file paths in the v9.3 patch do not have the same prefixes that the previous versions do and breaks install.sh.

Attempting to run install.sh gives messages like the following. Note that the last line is a prompt for user input:
```
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- src/ls.c   2023-03-13 14:08:10.000000000 -0400
|+++ src/ls.c   2023-07-02 16:10:41.947444700 -0400
--------------------------
File to patch:
```

It also breaks things like using nix's `fetchpatch` function to fetch the patch in order to  apply it to coreutils.

**Comment by yellowhat** [comment]
I had the same problem.
I modified the patch with:

```
--- coreutils-9.3/src/ls.c	2023-03-13 14:08:10.000000000 -0400
+++ coreutils-9.3/src/ls.c	2023-07-02 16:10:41.947444700 -0400
```

**Comment by jarun** [comment]
@yellowhat can you please raise a PR?
